<?php
/***********************************************************************************/
/* WARNING:                                                                        */
/* The wp-config.php file is automatically generated by Flywheel. You will not be  */
/* able to edit this file yourself. Defines needed for plugins can be added to a   */
/* php file in your wp-content/mu-plugins directory. If you need to add defines    */
/* for core WordPress functionality, please contact Flywheel support at            */
/* help@getflywheel.com.                                                           */
/***********************************************************************************/

define('FLYWHEEL_CONFIG_DIR', dirname(__FILE__) . '/flywheel-config');
define('FLYWHEEL_PLUGIN_DIR', FLYWHEEL_CONFIG_DIR . '/plugins');
define('FLYWHEEL_DEFAULT_PROTOCOL', 'http://');
define('WPMU_PLUGIN_DIR', dirname(__FILE__) . '/wp-content/mu-plugins');
define('WPMU_PLUGIN_URL', '/wp-content/mu-plugins');
define('FS_METHOD', 'direct');
define('WP_POST_REVISIONS',  10);
define('WP_MEMORY_LIMIT', '200M');




/****************************************************************************/
/*                         Database Configuration                           */
/****************************************************************************/
define('DB_NAME', 'db8503305935');
define('DB_USER', 'fw1123258706');
define('DB_PASSWORD', 'muX87I4cxYQr2brQkYpmz60hDJ1tW2');
define('DB_HOST', '127.0.0.1');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
$table_prefix  = 'wp_xjoz1nkutq_';






/****************************************************************************/
/*                             WordPress Salts                              */
/****************************************************************************/
define('AUTH_KEY',          ']ZES)k&9`Z^@HZ_fzb&Q@:C{2.{h4p:@&(Z8D=:)Z(g)sEVMA_nQ<L9!3Sm7oEK@');
define('SECURE_AUTH_KEY',   'd$8#6*r,5~I`DrZ6`sUyN~mIjI@2lu`8&k.,i(IClLyPyaBF6*.~L<k}i(L#6(CU');
define('LOGGED_IN_KEY',     '%bkITDwN6c@P-T?UD4.a,5qzu,Qbt~#by^6JMD031CeCnM/#uz3b;S&5ay9MOAhp');
define('NONCE_KEY',         'Y{q!jF!XM*m}J9Fb<+7MK1rcdB9GC^#E[Fn!p<8n}yf/X^2e5Z,5u#U1Tb<=M*@&');
define('AUTH_SALT',         'ULn&;V~^PHLcZ`!.)1a?)wQLLyMGc(@;n8]m34r~%]I6yjK[<x[{bEMgqIBaP1rF');
define('SECURE_AUTH_SALT',  'hvvi0=wjo(I~[Dz.8JY^/8B9QB%)2`r1(D+l3ZjU$h--{Ge#3>!$`Sa<$BqDE<Vq');
define('LOGGED_IN_SALT',    's[%yc4IL>[%])[SkX.gX_q|TOvfLRX^)5-Fh-@]8)1`D(RGg,6KbaNP-{bGjQ+wQ');
define('NONCE_SALT',        '^#^^;3sEDbWOupTQa$0#y^fZ~4J%h|17dcy.+al1$q]I{/!SD)~Y@!;.K2v:&e[V');


/****************************************************************************/
/*                        General WordPress Settings                        */
/****************************************************************************/
define('WPLANG', '');
define('WP_DEBUG', false);
define('WP_CACHE', false);
define('WP_DEBUG_LOG', false);




/****************************************************************************/
/*                     Disable WordPress Auto-updates                       */
/*           http://getflywheel.com/flywheel-wordpress-3-7/                 */
/****************************************************************************/
define('WP_AUTO_UPDATE_CORE', false);


if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

if ( array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
	$_SERVER['HTTPS']='on';



require_once(ABSPATH . 'wp-settings.php');
